// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	showMonitorWindow: () => typedError<null, string>(__TAURI_INVOKE("show_monitor_window")),
	getMonitorSessions: () => typedError<SessionInfo[], string>(__TAURI_INVOKE("get_monitor_sessions")),
	/**
	 *  v1 占位：不实现真实打开终端，按编译目标 OS 返回标识字符串作为 Err。
	 *  前端（任务 23）用 `t('terminal:toast.unsupported', { os })` 插值生成最终 toast 文案——
	 *  不在后端做 i18n，以便语言切换跟随，并复用 Phase B 任务 5 已预埋的 `{{os}}` 资源。
	 * 
	 *  参数为 v2 预留：session_id 用于定位 cwd、app 用于调 shell plugin。v1 用 `let _ =` 抑制 warning。
	 */
	openTerminal: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("open_terminal", { sessionId })),
	showSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_settings_window")),
	getConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_config", { key })),
	setConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_config", { key, value })),
};

/* Types */
/**
 *  set_config 命令成功后通过 `config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type ConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/config.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**  终端会话快照。MonitorApp 渲染 SessionCard 列表的数据源。 */
export type SessionInfo = {
	sessionId: string,
	cwd: string,
	projectName: string,
	title: string,
	status: SessionStatus,
	/**  最后活动时间（毫秒时间戳）。前端据此渲染相对时间（刚刚 / N 分钟前）。 */
	lastActivity: number,
};

/**  终端会话状态。前端 SessionCard 据此切换状态 Chip 配色与文案。 */
export type SessionStatus = "Running" | "NeedsConfirmation" | "Completed";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

