// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	showPanelWindow: () => typedError<null, string>(__TAURI_INVOKE("show_panel_window")),
	getClaudeSessions: () => typedError<ClaudeSessionInfo[], string>(__TAURI_INVOKE("get_claude_sessions")),
	/**
	 *  手动刷新会话列表：触发全量重扫并广播 claude-sessions:changed，
	 *  订阅该事件的前端窗口（pet_task / panel）自动收到新快照。
	 */
	refreshSessions: () => typedError<null, string>(__TAURI_INVOKE("refresh_sessions")),
	/**
	 *  跳转到 pid 对应的宿主终端会话。
	 *  成功返回 Ok(())；失败 emit `claude-sessions:nav-failed` 事件，
	 *  前端据 NavErr.kind 渲染差异化 toast。
	 */
	navigateToClaudeSession: (pid: number) => typedError<null, string>(__TAURI_INVOKE("navigate_to_claude_session", { pid })),
	/**
	 *  用指定编辑器 CLI 打开项目目录。editor 仅允许 "vscode" / "idea" 两个枚举值，
	 *  映射到 code / idea 命令；spawn 不阻塞（编辑器是长期运行的 GUI 进程）。
	 *  命令不存在 / 启动失败返回 Err(String)，前端自行 warn 或提示。
	 */
	openInEditor: (editor: string, cwd: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { editor, cwd })),
	/**
	 *  判断 cwd 是否 Java 项目（Maven pom.xml 或 Gradle build.gradle/build.gradle.kts）。
	 *  前端据此禁用 VSCode/IDEA 中不合适的那一个，保留两个按钮便于未来扩展。
	 */
	isJavaProject: (cwd: string) => __TAURI_INVOKE<boolean>("is_java_project", { cwd }),
	showPetWindow: () => typedError<null, string>(__TAURI_INVOKE("show_pet_window")),
	hidePetWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_window")),
	togglePetWindow: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_pet_window")),
	/**  查询桌宠当前显隐状态。供前端启动时初始化 UI。 */
	getPetVisibilityState: () => __TAURI_INVOKE<boolean>("get_pet_visibility_state"),
	/**
	 *  显示 pet_task 面板：仅当 pet 可见且存在活跃会话（Busy+Waiting）时 show + 定位，
	 *  否则 hide。显隐主导权在 pet 前端（基于 claude-sessions:changed payload 的 count），
	 *  本命令作为前端驱动入口；pet 显隐命令也调用它做联动兜底。
	 * 
	 *  活跃会话口径与前端 isActiveClaudeSession / countActiveClaudeSessions 一致（SSOT: sessionStatus.ts）。
	 */
	showPetTask: () => typedError<null, string>(__TAURI_INVOKE("show_pet_task")),
	/**
	 *  隐藏 pet_task 面板。pet 隐藏时由后端 hide_pet_window 命令联动调用，
	 *  避免孤立的悬浮列表；pet 前端 count 归零时也主动调用。
	 */
	hidePetTask: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_task")),
	/**
	 *  前端测得实际内容高度后回调，调整窗口高度并重新定位以保持与 pet 中心水平对齐。
	 *  由 PetTaskApp 的 ResizeObserver（rAF 节流）触发；窗口已可见，不需 show。
	 *  高度变化时 Y 按 panel 中心 = pet 中心重算，保证增减会话不破坏水平对齐。
	 */
	fitPetTask: (height: number | null) => typedError<null, string>(__TAURI_INVOKE("fit_pet_task", { height })),
	showSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_settings_window")),
	getConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_config", { key })),
	setConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_config", { key, value })),
};

/* Types */
/**
 *  终端会话快照。ClaudeSessionsPage 渲染 ClaudeSessionCard 列表的数据源；
 *  PetApp 聚合所有会话取"最忙"状态作为桌宠展示态。
 */
export type ClaudeSessionInfo = {
	/**  Claude Code 进程 pid（也是 `~/.claude/sessions/<pid>.json` 的文件名）。 */
	pid: number,
	/**  Claude Code 会话 ID（uuid）。从 json 的 `sessionId` 字段读取。 */
	sessionId: string,
	/**  会话工作目录绝对路径。 */
	cwd: string,
	/**  projectName = basename(cwd)，用于 UI 展示与 AppleScript 模糊匹配。 */
	projectName: string,
	/**  会话状态（Busy/Waiting/Idle/Dead）。 */
	status: ClaudeSessionStatus,
	/**  会话启动时间（毫秒时间戳）。对应 json 的 `startedAt`。 */
	startedAt: number,
	/**  最后一次状态更新时间（毫秒时间戳）。对应 json 的 `updatedAt`。 */
	updatedAt: number,
	/**  宿主终端应用类型，决定跳转策略。 */
	hostApp: TerminalApp,
	/**  宿主终端进程 pid（用于 AppleScript 间接定位）。 */
	hostPid: number,
	/**
	 *  宿主终端的 tty 设备路径（如 `/dev/ttys004`），AppleScript 精确匹配用。
	 *  无法识别时为空字符串。
	 */
	tty: string,
};

/**
 *  终端会话状态。直接映射 `~/.claude/sessions/<pid>.json` 里的 `status` 字段
 *  （busy/waiting/idle）外加本地推断的 Dead（进程已退出但 json 残留）。
 *  前端 ClaudeSessionCard 据此切换状态 Chip 配色与文案。
 */
export type ClaudeSessionStatus = 
/**  运行中：Claude 正在执行工具/生成回复。 */
"Busy" | 
/**  等待输入：Claude 已完成回复，等用户输入。 */
"Waiting" | 
/**  空闲：会话长时间无活动，但仍存活。 */
"Idle" | 
/**  已失效：进程已退出，json 残留。discover 阶段会过滤掉，理论上不会出现在前端。 */
"Dead";

/**
 *  set_config 命令成功后通过 `config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type ConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/config.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**  跳转失败原因。对应前端 navigation-failed toast 文案细分。 */
export type NavErr = 
/**  宿主终端未识别（如 VSCode 内嵌 / Wezterm 等）。 */
{ kind: "unsupportedHostApp" } | 
/**  osascript 执行失败（exit code 非零）。 */
{ kind: "osaScriptFailed"; stderr: string } | 
/**  ClaudeSessionStore 找不到对应 pid 的会话（可能刚过期）。 */
{ kind: "sessionNotFound" } | 
/**  其他 IO 错误。 */
{ kind: "io"; message: string };

/**
 *  宿主终端应用。通过 `ps -p <ppid>` 链式反查 Claude 进程的祖先进程名得出。
 *  用于决定跳转时调用哪个 AppleScript 脚本。
 */
export type TerminalApp = "ITerm2" | "Terminal" | "IntelliJ" | 
/**  未识别的宿主终端（如 VSCode 内嵌、Wezterm、Alacritty 等）。跳转按钮将禁用。 */
"Unknown";

/**  Y/N 布尔风格配置值。serde rename 到单字母，序列化与 specta 导出均为 "Y"/"N"。 */
export type YesNo = "Y" | "N";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

