// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	showPanelWindow: (navigateTo: string | null) => typedError<null, string>(__TAURI_INVOKE("show_panel_window", { navigateTo })),
	getClaudeSessions: () => typedError<ClaudeSessionInfo[], string>(__TAURI_INVOKE("get_claude_sessions")),
	/**
	 *  手动刷新会话列表：触发全量重扫并广播 claude-sessions:changed，
	 *  订阅该事件的前端（panel 的 ClaudeSessionsPage 页、pet_claude_sessions_summary、pet_claude_sessions_task）自动收到新快照。
	 *  force_git=true：手动刷新强制重算空闲会话的 GitPending，立即反映最新 git 状态。
	 */
	refreshSessions: () => typedError<null, string>(__TAURI_INVOKE("refresh_sessions")),
	/**
	 *  跳转到 pid 对应的宿主终端会话。
	 *  成功返回 Ok(())；失败 emit `claude-sessions:nav-failed` 事件，
	 *  前端据 NavErr.kind 渲染差异化 toast。
	 */
	navigateToClaudeSession: (pid: number) => typedError<null, string>(__TAURI_INVOKE("navigate_to_claude_session", { pid })),
	/**
	 *  用指定编辑器打开项目目录。
	 * 
	 *  **macOS**：GUI 应用从 Dock/Finder 启动时继承的 PATH 仅 `/usr/bin:/bin:/usr/sbin:/sbin`，
	 *  不含 `/usr/local/bin`——直接 spawn `code` / `idea` CLI 会 ENOENT（用户在终端手动执行
	 *  `code` 能用是因为 shell 读 ~/.zshrc 补全了 PATH；从 .app bundle 启动则不走 shell 流程）。
	 *  改用 macOS 原生 `open -a <App>`：`open` 在 /usr/bin 不依赖 PATH，由 LaunchServices 解析
	 *  应用。IDEA 应用名因版本而异（CE/Ultimate/EDU），依次尝试候选名，首个成功即返回。
	 * 
	 *  **Windows / Linux**：GUI 应用继承的 PATH 通常含编辑器安装目录（VSCode 安装时默认勾选
	 *  Add to PATH，IDEA 由 JetBrains Toolbox 创建 shell link），直接走 `code` / `idea` CLI 即可。
	 * 
	 *  editor 仅允许 "vscode" / "idea"；应用未安装 / 启动失败返回 Err(String)，前端 warn。
	 */
	openInEditor: (editor: string, cwd: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { editor, cwd })),
	/**
	 *  判断 cwd 是否 Java 项目（Maven pom.xml 或 Gradle build.gradle/build.gradle.kts）。
	 *  前端据此禁用 VSCode/IDEA 中不合适的那一个，保留两个按钮便于未来扩展。
	 */
	isJavaProject: (cwd: string) => __TAURI_INVOKE<boolean>("is_java_project", { cwd }),
	/**
	 *  用指定终端打开目录。仅 macOS 支持；terminal 仅允许 "iterm2" / "terminal"。
	 *  有窗口则新建 Tab，无窗口则新建窗口，并 cd 到指定目录。
	 *  iTerm2 模式下根据 `iterm2_split_direction` 配置决定分屏方向（默认上下分屏）。
	 */
	openInTerminal: (terminal: string, dir: string) => typedError<null, string>(__TAURI_INVOKE("open_in_terminal", { terminal, dir })),
	showPetClaudeSessionsSummaryWindow: () => typedError<null, string>(__TAURI_INVOKE("show_pet_claude_sessions_summary_window")),
	hidePetClaudeSessionsSummaryWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_claude_sessions_summary_window")),
	togglePetClaudeSessionsSummaryWindow: () => typedError<boolean, string>(__TAURI_INVOKE("toggle_pet_claude_sessions_summary_window")),
	/**  查询桌宠当前显隐状态。供前端启动时初始化 UI。 */
	getPetClaudeSessionsSummaryVisibilityState: () => __TAURI_INVOKE<boolean>("get_pet_claude_sessions_summary_visibility_state"),
	/**
	 *  显示 pet_claude_sessions_task 面板：仅当 pet 可见且存在待关注会话（Busy+Waiting+GitPending）时 show + 定位，
	 *  否则 hide。显隐主导权在 pet 前端（基于 claude-sessions:changed payload 的 count），
	 *  本命令作为前端驱动入口；pet 显隐命令也调用它做联动兜底。
	 * 
	 *  待关注会话口径与前端 isAttentionClaudeSession / countAttentionClaudeSessions 一致（SSOT: claudeSessionStatus.ts）。
	 *  含 GitPending：用户 commit 后空闲会话仍需展示"待提交"，与"仅活跃"语义升级为"待关注"。
	 */
	showPetClaudeSessionsTaskWindow: () => typedError<null, string>(__TAURI_INVOKE("show_pet_claude_sessions_task_window")),
	/**
	 *  隐藏 pet_claude_sessions_task 面板。pet 隐藏时由后端 hide_pet_claude_sessions_summary_window 命令联动调用，
	 *  避免孤立的悬浮列表；pet 前端 count 归零时也主动调用。
	 */
	hidePetClaudeSessionsTaskWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_pet_claude_sessions_task_window")),
	/**
	 *  前端测得实际内容高度后回调，调整窗口高度并重新定位以保持与 pet 中心水平对齐。
	 *  由 PetClaudeSessionsTaskApp 的 ResizeObserver（rAF 节流）触发；窗口已可见，不需 show。
	 *  高度变化时 Y 按 panel 中心 = pet 中心重算，保证增减会话不破坏水平对齐。
	 */
	fitPetClaudeSessionsTask: (height: number | null) => typedError<null, string>(__TAURI_INVOKE("fit_pet_claude_sessions_task", { height })),
	showSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_settings_window")),
	getConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_config", { key })),
	setConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_config", { key, value })),
	/**  列出全部仓库（按最近提交时间倒序）。零 git 解析，即时返回。 */
	listRepositories: () => typedError<Repository[], string>(__TAURI_INVOKE("list_repositories")),
	/**
	 *  添加仓库。**严格校验**：名称/目录非空、目录为存在的绝对路径、且为 git 仓库；
	 *  dir 唯一（重复返回哨兵 "dir-exists"）；sub_dir_list 每项拼接目录须存在（否则 "invalid-sub-dir"）。
	 *  校验通过后解析 git 信息并入库，返回新仓库。
	 */
	addRepository: (name: string, dir: string, description: string, subDirList: RepoSubDir[]) => typedError<Repository, string>(__TAURI_INVOKE("add_repository", { name, dir, description, subDirList })),
	/**
	 *  更新仓库的名称、目录、描述与子目录列表。校验新目录须为 git 仓库且不与其他记录重复；
	 *  sub_dir_list 每项拼接目录须存在。校验通过后重新解析 git 信息并更新，返回更新后的仓库。
	 */
	updateRepository: (id: number, name: string, dir: string, description: string, subDirList: RepoSubDir[]) => typedError<Repository, string>(__TAURI_INVOKE("update_repository", { id, name, dir, description, subDirList })),
	/**  删除仓库。 */
	deleteRepository: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_repository", { id })),
	/**  刷新单个仓库：重解析 git 信息并更新，返回新数据。 */
	refreshRepository: (id: number) => typedError<Repository, string>(__TAURI_INVOKE("refresh_repository", { id })),
	/**
	 *  全量刷新：遍历重解析全部仓库并更新，返回新列表。
	 *  async + spawn_blocking：git 子进程操作让出 async 线程，不阻塞其他 IPC 调用。
	 */
	refreshAllRepositories: () => typedError<Repository[], string>(__TAURI_INVOKE("refresh_all_repositories")),
	/**  用系统文件管理器打开目录。dir 必须为存在的绝对路径。 */
	openInFileManager: (dir: string) => typedError<null, string>(__TAURI_INVOKE("open_in_file_manager", { dir })),
	/**  列出 app.db 全部用户表及其行数（只读）。前端「应用数据库」页左侧表列表数据源。 */
	listAppDbTables: () => typedError<AppDbTableInfo[], string>(__TAURI_INVOKE("list_app_db_tables")),
	/**  导出 app.db 指定表的列名 + 全部行（只读）。表名经白名单 + 存在性双重校验，防注入。 */
	dumpAppDbTable: (table: string) => typedError<AppDbTableDump, string>(__TAURI_INVOKE("dump_app_db_table", { table })),
};

/* Types */
/**  dump_app_db_table 返回：一张表的列名 + 全部行。每个单元格为 AppDbValue，前端按 kind 渲染。 */
export type AppDbTableDump = {
	/**  列名，顺序与 rows 中每行单元格一致。 */
	columns: string[],
	/**  行数据：每行为与 columns 等长、同序的单元格值数组。 */
	rows: AppDbValue[][],
};

/**  app.db 中一张用户表的概要（list_app_db_tables 返回项）。前端「应用数据库」页左侧表列表数据源。 */
export type AppDbTableInfo = {
	/**  表名（来自 sqlite_master，已排除 sqlite_% 内部表）。 */
	name: string,
	/**
	 *  表行数（`SELECT COUNT(*)`）。非常规表名无法安全拼接 COUNT，记 -1 供前端禁用浏览。
	 *  i32 收窄：本地配置库行数远小于 2^31。
	 */
	rowCount: number,
};

/**
 *  dump_app_db_table 中一个单元格的值。SQLite 动态类型 → 跨边界枚举，前端按 kind 渲染。
 *  Integer 为 i64（时间戳等大数），specta 用 Number 映射为 TS number（值 < 2^53 精度安全）。
 *  Blob 不透传二进制（避免控制字符污染前端 JSON），仅传字节数供前端展示占位。
 */
export type AppDbValue = { kind: "null" } | { kind: "integer"; value: number } | { kind: "real"; value: number | null } | { kind: "text"; value: string } | 
/**  Blob 字节数（i32 收窄：单 cell blob 远小于 2^31）。 */
{ kind: "blob"; bytes: number };

/**
 *  终端会话快照。ClaudeSessionsPage 渲染 ClaudeSessionCard 列表的数据源；
 *  PetClaudeSessionsSummaryApp 聚合所有会话取"最忙"状态作为桌宠展示态。
 */
export type ClaudeSessionInfo = {
	/**  Claude Code 进程 pid（也是 `~/.claude/sessions/<pid>.json` 的文件名）。 */
	pid: number,
	/**  Claude Code 会话 ID（uuid）。从 json 的 `sessionId` 字段读取。 */
	sessionId: string,
	/**  会话工作目录绝对路径。 */
	cwd: string,
	/**  projectName = basename(cwd)，用于 UI 展示与 AppleScript 模糊匹配。 */
	projectName: string,
	/**  会话状态（Busy/Waiting/Idle/GitPending/Dead）。 */
	status: ClaudeSessionStatus,
	/**  会话启动时间（毫秒时间戳）。对应 json 的 `startedAt`。 */
	startedAt: number,
	/**  最后一次状态更新时间（毫秒时间戳）。对应 json 的 `updatedAt`。 */
	updatedAt: number,
	/**  宿主终端应用类型，决定跳转策略。 */
	hostApp: TerminalApp,
	/**  宿主终端进程 pid（用于 AppleScript 间接定位）。 */
	hostPid: number,
	/**
	 *  宿主终端的 tty 设备路径（如 `/dev/ttys004`），AppleScript 精确匹配用。
	 *  无法识别时为空字符串。
	 */
	tty: string,
};

/**
 *  终端会话状态。直接映射 `~/.claude/sessions/<pid>.json` 里的 `status` 字段
 *  （busy/waiting/idle）外加两个本地推断状态：GitPending（空闲且有未提交改动）与
 *  Dead（进程已退出但 json 残留）。前端 ClaudeSessionCard 据此切换状态 Chip 配色与文案。
 */
export type ClaudeSessionStatus = 
/**  运行中：Claude 正在执行工具/生成回复。 */
"Busy" | 
/**  等待输入：Claude 已完成回复，等用户输入。 */
"Waiting" | 
/**  空闲：会话长时间无活动，但仍存活。 */
"Idle" | 
/**
 *  本地派生：会话空闲（base=Idle）且其 cwd 存在未提交 git 改动（含 untracked）。
 *  由 `store::rescan` 在 enrich 后二次判定，不来自 Claude json。
 *  有界过期：fs watcher 触发的 rescan（force_git=false）复用上次缓存值，
 *  poll（60s）/手动刷新（force_git=true）强制重算，避免 watcher 高频跑 git。
 */
"GitPending" | 
/**  已失效：进程已退出，json 残留。discover 阶段会过滤掉，理论上不会出现在前端。 */
"Dead";

/**
 *  set_config 命令成功后通过 `config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type ConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/config.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**  跳转失败原因。对应前端 navigation-failed toast 文案细分。 */
export type NavErr = 
/**  宿主终端未识别（如 VSCode 内嵌 / Wezterm 等）。 */
{ kind: "unsupportedHostApp" } | 
/**  osascript 执行失败（exit code 非零）。 */
{ kind: "osaScriptFailed"; stderr: string } | 
/**  ClaudeSessionStore 找不到对应 pid 的会话（可能刚过期）。 */
{ kind: "sessionNotFound" } | 
/**  其他 IO 错误。 */
{ kind: "io"; message: string };

/**
 *  仓库下的一个项目子目录项。一个仓库可对应多个项目子目录（monorepo 多 package）。
 *  `sub_dir_list` 在 SQLite 中以 JSON 字符串存储，跨边界时 serde 在 `Vec<RepoSubDir>` ↔ 文本间转换。
 */
export type RepoSubDir = {
	/**  项目子目录相对仓库目录的路径（如 `packages/web`）。后端校验拼接目录须存在。 */
	subDir: string,
	/**  该子目录的描述（用户填写，可空，最多 200 字）。 */
	subDirDescription: string,
};

/**
 *  本地仓库记录。持久化在 SQLite `repositories` 表（见 shared/repositories.rs）。
 *  RepositoriesPage 渲染 RepositoryCard 列表的数据源。
 * 
 *  `name` / `dir` / `description` / `sub_dir_list` 由用户在添加表单填写；`remote_url` / `branch` / `last_commit_*`
 *  由 `parse_repo_info` 跑 git CLI 解析，add/refresh 时写入；`updated_at` 为最近一次刷新时间。
 *  解析失败的字段留空字符串 / 0 时间戳，前端据 `card.noRemote` / `card.noCommit` 兜底文案。
 */
export type Repository = {
	/**
	 *  自增主键（SQLite INTEGER PRIMARY KEY）。用 i32 而非 i64：本地仓库列表规模远小于 2^31，
	 *  且 specta 禁止裸 i64 跨边界导出（BigInt 精度），i32 映射 TS number 无需 Number 注解。
	 */
	id: number,
	/**  用户填写的仓库名称（展示用，可重复）。新增模式下由仓库目录 basename 自动派生，项目子目录不影响。 */
	name: string,
	/**  仓库目录绝对路径（UNIQUE，严格校验须存在且为 git 仓库）。 */
	dir: string,
	/**  仓库级描述（用户填写，可空，最多 200 字）。卡片在「当前分支」下方单行展示，悬浮显示完整内容。 */
	description: string,
	/**  项目子目录列表（可空数组）。VSCode/IDEA/iTerm2 通过菜单选择其中一项，以「仓库目录 + 子目录」打开。 */
	subDirList: RepoSubDir[],
	/**  `git remote get-url origin` 结果，无 origin 时为空字符串。 */
	remoteUrl: string,
	/**  `git rev-parse --abbrev-ref HEAD` 结果，detached HEAD / 无提交时为空字符串。 */
	branch: string,
	/**  最近一次提交时间（毫秒时间戳，`git log -1 --format=%ct` ×1000）。无提交时为 0。 */
	lastCommitAt: number,
	/**  最近一次提交的标题（`git log -1 --format=%s`）。无提交时为空字符串。 */
	lastCommitMessage: string,
	/**  本记录最近一次刷新时间（毫秒时间戳），add/refresh 时写入。 */
	updatedAt: number,
};

/**
 *  宿主终端应用。通过 `ps -p <ppid>` 链式反查 Claude 进程的祖先进程名得出。
 *  用于决定跳转时调用哪个 AppleScript 脚本。
 */
export type TerminalApp = "ITerm2" | "Terminal" | "IntelliJ" | 
/**  未识别的宿主终端（如 VSCode 内嵌、Wezterm、Alacritty 等）。跳转按钮将禁用。 */
"Unknown";

/**  Y/N 布尔风格配置值。serde rename 到单字母，序列化与 specta 导出均为 "Y"/"N"。 */
export type YesNo = "Y" | "N";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

